# Site settings
title: CarlPham Blog's
header-img: img/home-bg.jpg
email: capham.vn@gmail.com
copyright_name: CarlPham
description: "CarlPham blog's talks about programming and life"
baseurl: ""
url: "http://carlpham.com"
twitter_username: 
github_username:  CarlPham
facebook_username:  pham.vanca.7
email_username:  capham.vn@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: 57650785

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
